### ISSUE TITLE
Can't locate Catalyst/Plugin/Session/State/Cookie.pm in @INC

### ISSUE THREAD

**Issue by eserte** [sebmourlhou/catalyst-plugin-oidc#1]
The test suite fails if Catalyst::Plugin::Session::State::Cookie is not installed --- probably a missing prerequisite specification?
```
Can't locate Catalyst/Plugin/Session/State/Cookie.pm in @INC (you may need to install the Catalyst::Plugin::Session::State::Cookie module) (@INC entries checked: ...  .) at /usr/perl5.41.12/lib/site_perl/5.41.12/Class/Load.pm line 174.
Compilation failed in require at /usr/perl5.41.12/lib/site_perl/5.41.12/Catalyst/Test.pm line 155.
t/auth-code-flow-IT.t ... 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
Can't locate Catalyst/Plugin/Session/State/Cookie.pm in @INC (you may need to install the Catalyst::Plugin::Session::State::Cookie module) (@INC entries checked: ...  .) at /usr/perl5.41.12/lib/site_perl/5.41.12/Class/Load.pm line 174.
Compilation failed in require at /usr/perl5.41.12/lib/site_perl/5.41.12/Catalyst/Test.pm line 155.
t/resource-server-IT.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

**Comment by sebmourlhou** [comment]
The dependencies have been fixed. It should work with the new version (0.03)
